name: Windows (MinGW)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup cmake"
        run: cmake --version

      - name: "Setup gil"
        run: |
          pip3 install gil
          gil update

      - name: "Build"
        run: |
          $env:INCLUDE = "C:\mingw64\x86_64-w64-mingw32\include;$env:INCLUDE"
          $env:LIB = "C:\mingw64\x86_64-w64-mingw32\lib;$env:LIB"
          $env:PATH = "C:\mingw64\bin;$env:PATH"
          cd build
          ./mingw.bat
